### PR TITLE
JS visualization improvements - zoom & pan and doubleclicks.

### PR DESCRIPTION
**Pull request by BoZenKhaa**
As I am using the tool with deep trees, I am hacking away on some improvements to the js visualization that I would like to merge in the future in some way. 

The improvements are:

-  _Double click expands 2 layers_ - this is useful for me since I currently work with trees where "chance" nodes alternate with "states". This behavior is only active when `on_click_display_depth==1`
- _Zoom and pan_ - with the current implementation, the deep tree is rendered in static space, which means that nodes start to overlap pretty soon. Zoom and pan address this drawback. On the other hand, this change means that one has to zoom and pan even with smaller trees, and it can also make generating figures more difficult. The "density" of the tree is controlled by the  d3 tree property `nodeSize`.

https://user-images.githubusercontent.com/1710518/188833966-f65b77ec-4c71-4c6c-9d29-b030182220bd.mp4

This PR is to discuss whether and how to incorporate these changes with the existing code. 

Also, that js code is mostly trial and error pasted from SO, if anyone knows javascript, I would appreciate any help or tips on how to clean up the code.

### CODE REVIEW

**Comment by zsunberg** [comment]
Oh wow, this is very cool!! Is it ready to merge now?

**Comment by BoZenKhaa** [comment]
Regarding zoom and pan, the only thing I would like to add is to expose the node spacing parameters in the Julia API. 
Unless you care about retaining the existing visualization behavior, then I would have to add some messy `if`s to the javascript.

**Comment by zsunberg** [comment]
> the only thing I would like to add is to expose the node spacing parameters in the Julia API

That seems reasonable

> Unless you care about retaining the existing visualization behavior, then I would have to add some messy ifs to the javascript.

Are there any advantages to the current behavior over the new behavior? If those advantages are small, I am happy to get rid of the old behavior.

**Comment by BoZenKhaa** [comment]
The main difference is that with zoom and pan, even smaller trees that previously rendered compactly into the display area will now have to be panned around. But I think that compact spacing with similar results can still be achieved by playing with the spacing parameters.

This would probably be an issue only for people trying to generate figures with the tool. 

I will check if the old behavior could be retained gracefully, but if not, I am for abandoning it as well.

**Comment by zsunberg** [comment]
Ok, thanks for your work on this!

**Comment by BoZenKhaa** [comment]
Sorry, I got busy with the start of the semester. I think it's okay to merge now. The old node spacing behavior is now only available through uncommenting a line in javascript.

**Comment by BoZenKhaa** [comment]
Sorry for the mess, I removed the superfluous changes. It might be a good idea to squash this PR when merging.

**Comment by zsunberg** [comment]
Thanks @BoZenKhaa sorry I couldn't look at this earlier in the week!

**Comment by zsunberg** [comment]
Thanks @BoZenKhaa sorry I couldn't look at this earlier in the week!

**Pull request merged**
