### PR TITLE
Added support for custom attributes in trees created via the AbstractTrees API

### PR DESCRIPTION
**Pull request by ebalaban**

### CODE REVIEW

**Comment by zsunberg** [comment]
Thanks! Yeah, I think this is a good idea. I want to make a tweak or two before merging though. Will do that today or tomorrow.

**Comment by ebalaban** [comment]
Sure thing, thanks Zach. No rush. Also, perhaps a minor release can be 
done after the merge? This way people won't have to manually track 
'master' to get this and a couple of preceding bug fixes/improvements.

**Comment by zsunberg** [comment]
Ok @ebalaban does this work for the purpose you had in mind. If it does, I'll merge it.

**Comment by ebalaban** [comment]
Yes, works very nicely. Thanks!

**Comment by zsunberg** [comment]
Cool. Thanks for the idea of improving the AbstractTrees interface

**Pull request merged**
