### PR TITLE
Lazy loading of deep trees using `children` interface with HTTP.jl

### PR DESCRIPTION
**Pull request by BoZenKhaa**
Implements lazy loading of deep trees. The tree needs to be defined with the `children` interface from AbstractTrees.jl. To see it in action,  check out the `LazyLoadDeepTrees.ipynb`

I would appreciate any feedback regarding the structure, usage, and parameter names.  Also, tips on how to prioritize and approach some of the todos are welcome.

## How it works:

`D3Tree` takes a new parameter, `max_expand_depth=1` that limits the depth of the calls to `children`. This leaves some leaf nodes unexpanded:

1. If an unexpanded node is clicked in the javascript visualization client, it uses `fetch` with `GET` method to request the corresponding subtree from a `HTTP.jl` localhost server.
2.  The server expands the leaf node using the `children` method and sends the corresponding subtree as json to the visualization client,
3. Client visualization javascript updates the data structures and the visualization. 

The result is that trees even with large branching factors can be explored to very large depths without taking lots of memory and time to compute and visualize:
image

Thought this was going to be a quick and simple project to help me visualize large problems, but it took really long time. It didn't help I had no clue about javascript and network stuff. This started with WebSockets, then switched to HTTP and I almost switched back to WebSockets before figuring out CORS. 

## Todos
Later, I need to:

- [x] cleanup and add server tests, 
- [x] turn off logging by default, or remove logging, 
- [x] check and add error handling on the Julia side,  
- [x] update README
- [x] remove commented and debugging code,
- [x] clean up imports,
- [x] add docstrings, 
- [x] apply CORS headers to server 404 and 405 responses,
- [x] make server persistent (no restarts in `show`) and reliable,
- [x] ~~limit lifetime of `TREE_DATA` entries,~~ make it user responsibility and add method for that
- [ ] set minimum vertical distance of nodes and add vertical scrollbar to the visualization
- [ ] ~~(Maybe) test the javascript, but I have no clue how to do that,~~
- [ ] (Maybe) do some error handling on the client-side, maybe display them as alerts to the user?
- [ ] ~~(Maybe) add console variant~~

### CODE REVIEW

**Comment by BoZenKhaa** [comment]
I think I might be done with this for now. I might try to figure out the scrollbars later since the overlapping labels can get annoying.

**Comment by zsunberg** [comment]
This looks really great! I will review it soon.

**Review by zsunberg — CHANGES_REQUESTED** [review]
Thanks for doing this! I think it looks good.

Before merging, I have two questions and one (nitpicky) request.

Question 1: Is there an option (perhaps a keyword argument) to completely disable the HTTP server and just load the tree the old way? It seems like that would be easy to implement in line 35 of show.jl and would be a good workaround if we ever find a problem with the HTTP lazy loading.

Question 2: Why did you choose to have 1 server for the package instead of 1 server per D3Tree? (this may be the right decision - just want to make sure it is thought through)

Request (nitpicky): Can you change the filenames of the new test files from camelCase to snake_case. I think that is more consistent with the style of most julia packages.

**Comment by BoZenKhaa** [comment]
Thanks for the comments!

**Regarding 1:**
The server should not start by default already since https://github.com/sisl/D3Trees.jl/blob/aeb41424d0e9dbeb6245bee2c03bd8fa99b34181/src/show.jl#L35 will only be true if the tree has unexpanded nodes. By default, `max_expand_depth` is the maximal integer https://github.com/sisl/D3Trees.jl/blob/aeb41424d0e9dbeb6245bee2c03bd8fa99b34181/src/D3Trees.jl#L60, and all nodes up to this depth are expanded in the initial json, which is just passed to the javascript through variable and not the server. So I think that any tree that can currently be rendered without needing the server will still render without it. Trees that are too large to display will not render anyway with the defaults and the server will only start up if `max_expand_depth` is set to a reasonably small number.

**Regarding 2:**
Do you see some potential benefits from having multiple servers? I was not sure about this and I considered also a separate server for each tree. The reasons I ended up doing it this way were:

- The server binds to a socket and occupies a single port. I think in HTTP and in general, two servers can't share the same port. So if I wanted a different server for a different tree, I would also need to consume multiple ports. The common practice seems to be to bind service to a single port, so that's what I did, and resolve different trees based on urls.
- The server starts an async task that consumes resources and ports. One server limits the consumed resources. But I am not sure whether this is relevant, the most expensive thing might be the storage of unexpanded tree nodes in TREE_DATA.

Thinking about this, the limitation of the current approach is that we can not run two servers on a single machine. So if there is a visualization in Jupyter and I run the test, the tests will fail since the server running in Jupyter already uses the port.

I actually think I should rewrite this slightly to avoid global variables so that the user can easily override the default port and use a different one in tests. This would probably make sense to pass to the tree here as kwarg https://github.com/sisl/D3Trees.jl/blob/aeb41424d0e9dbeb6245bee2c03bd8fa99b34181/src/D3Trees.jl#L101
and get it from the tree in `show`. Then, if a different port was specified, we could also just spawn a new server with it. 

**Nitpicks:**
Thank you for noticing that! I was looking at a lot of java code lately. Please, let me know if you have any more nitpicks 😀.

**Comment by zsunberg** [comment]
Great, thanks for thinking through these things - I agree with your decisions.

The `max_expand_depth` argument is a bit confusing to me. Could we switch to `lazy_expand_after_depth`? And I think we should switch the default to something less than `typemax(Int)` - maybe 10 or 20?

**Comment by zsunberg** [comment]
Let me know when you've thought about that argument name and once you're done I'll merge it.

**Comment by BoZenKhaa** [comment]
I thought about it, didn't come up with anything better, and I agree that `lazy_expand_after_depth` is more descriptive, so that's it now. I used `typemax` to retain the old behavior, but a lower number will do fine, right now it's set to 20.

**Comment by BoZenKhaa** [comment]
Good point. In general, this would not work right now. However, I usually tunnel through ssh to access Jupyter running on a server, and it would be straightforward also to tunnel the D3TreeServer port and then everything should work fine.

I think the remote server _could_ be made to work with any Jupyter server fairly quickly by, for a start, letting the user set the `host` for the fetch on the javascript side and opening the server port. But I am not sure whether this _should_ or _needs_ to be done. It might also not be secure to expose the D3TreeServer to the internet in the current state.

**Comment by BoZenKhaa** [comment]
Regarding error messages displayed in the visualization, I have not worked on that. Right now, any server errors can only be seen on the Julia log or in the javascript console, in the 4xx response messages. 

I would like to look at the javascript side of things some more later, especially some type variable height for the SVG or scrolling. For that, I would like to move the code to a newer version of d3 than v3. I found the [tree code for v5](https://bl.ocks.org/d3noob/1a96af738c89b88723eb63456beb6510/f2a2a09df5233e4dffea48d9598472da91a5eb1a), so that might be not that difficult.

By the way, for offline use, it seems it might be fairly straightforward to store the d3 javascript in a Julia artifact and just input it into the `show` HTML string as another `script` tag.

**Review by zsunberg — APPROVED** [review]

**Comment by zsunberg** [comment]
Yes, it would be great to improve the js side - we'll leave that for another PR.

Is this ready for merge now?

**Comment by BoZenKhaa** [comment]
Yep, I think so.

**Pull request merged**
